# Generated by Django 3.1.3 on 2021-09-03 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pair',
            name='from_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair_from_currency', to='trade.currency'),
        ),
        migrations.AddField(
            model_name='pair',
            name='to_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair_to_currency', to='trade.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('from_currency', 'to_currency')},
        ),
    ]
